apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: social-media
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: rachidjedata/social-media-backend:v1
        ports:
        - containerPort: 8000
        env:
          valueFrom: 
            configMapKeyRef:
              name: backend-config
          valueFrom:
            secretKeyRef:
              name: backend-secrets
        command: ["sh", "-c"]
        args: ["python manage.py migrate && gunicorn social_book.wsgi:application --bind 0.0.0.0:8000 --workers 4"]
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: social-media
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: backend