services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
      - rabbitmq
    environment:
      - CACHE_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    command: >
      sh -c "python manage.py migrate &&
             gunicorn social_book.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    networks:
      - frontend
      - backend

  db:
    container_name: db
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    networks:
      - backend

  celery_worker:
    build: ./backend
    command: celery -A social_book worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    networks:
      - backend
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 2
    networks:
      - backend

  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - backend

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000

volumes:
  postgres_data:
networks:
  frontend:
  backend:
