apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: social-media
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: rachidjedata/social-media-frontend:v1
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: backend-service
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: social-media
spec:
  type: NodePort # Or LoadBalancer for cloud providers
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: frontend