apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: social-media
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgres-secrets # Store your .env variables in a Kubernetes Secret
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-data

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: social-media
spec:
  ports:
  - port: 5432
  selector:
    app: postgres