# Generated by Django 5.2.6 on 2025-09-12 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likepost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="core.post",
            ),
        ),
    ]
