# Generated by Django 5.2.6 on 2025-09-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_post_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default="", upload_to="post_images"),
        ),
    ]
